services:
  honeyshell:
    container_name: honeyshell
    build:
      context: ./honeypot
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "22:22"
    networks:
      - honeypot_network
    restart: unless-stopped
  database:
    container_name: honeyshell_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - honeypot_network
    restart: unless-stopped

networks:
  honeypot_network:
    driver: bridge
